"""
@deprecated Moved to anson.py3/src/semantier.py
"""

from dataclasses import dataclass
from idlelib.browser import file_open
from typing import List, cast

from anson.io.odysz.anson import Anson

from src.anson.io.odysz.peers import gen_py, gen_cpp, gen_ts, AnsonAst, gen_entt


@dataclass
class SemanticSettings(Anson):
    """
    Mapping for gen.cmake.CSettings
    """
    src: str

    headers: List[str]
    '''
    @deprecated: for tree-sitter only, is replaced by AstConfig
    '''

    ###########################################################
    header: str
    json_h: str
    py: str
    ts: str

    # ansonMsg: str
    requests: List[List[str]]
    '''
    ASTs generated by anson.java AstHelper.
    '''

    def __init__(self):
        super().__init__()
        self.src = "src"
        self.headers = []
        self.json_h = "json.hpp"


def gen_peers(settings: SemanticSettings):
    count = 0
    entt_regs = []
    for astjson in settings.requests:
        ast = None
        with file_open(astjson, 'r') as f:
            ast = cast(AnsonAst, Anson.from_file(f))
        if ast is None:
            continue

        if settings.py:
            with file_open(settings.py, 'a' if count == 0 else 'w') as py:
                gen_py(py, ast)

        if settings.header:
            # with file_open(settings.header, 'w') as header, file_open(settings.json_h, 'w') as entt:
            with file_open(settings.header, 'a' if count == 0 else 'w') as header:
                entt_regs.append(gen_cpp(header, ast))

        if settings.ts:
            with file_open(settings.ts, 'a' if count == 0 else 'w') as ts:
                gen_ts(ts, ast)

        count = count+1

    if settings.json_h and count > 0:
        with file_open(settings.json_h, 'w') as entt:
            gen_entt(entt, entt_regs)
